version: "3"
services:
  mariadb:
    image: "mariadb:10.3.7"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "sme"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "devpass"
    ports:
      - "3306:3306"
    volumes:
      - "./target/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./.docker/storage/mariadb:/var/lib/mysql"
    networks:
      - backend
  mongodb:
    image: "mongo:4.0.0"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "dev"
      MONGO_INITDB_ROOT_PASSWORD: "devpass"
    ports:
      - "27017:27017"
    volumes:
      - "./target/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./.docker/storage/mongodb:/data/db"
    networks:
      - backend
networks:
  backend:
    driver: bridge