## Local profile
spring:
  profiles:
    active: local

  ## MariaDB
  datasource:
    name: sme-mts
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sme??characterEncoding=utf8
    username: dev
    password: devpass
    hikari:
      idle-timeout: 10000

  ## MongoDB
  data:
    mongodb:
      uri: mongodb://dev:devpass@127.0.0.1:27017

  ## Restful API endpoints
  jersey:
    type: filter
    applicationPath: '/api'
    uriVersioning: true

## Myabtis settings
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis-mappers/*.xml


## Logging settings
logging.file: /tmp/sme-mts.log
logging:
  level:
    root: info
    org.springframework.transaction.interceptor: trace # trace transaction status
  file:
    max-size: 10MB
    max-history: 10
  pattern:
    console: '[%d{YYYY-MM-dd HH:mm:ss.SSS}][%p][%t][%logger]%m%n'
    file: '[%d{YYYY-MM-dd HH:mm:ss.SSS}][%p][%t][%logger]%m%n'

---

## Docker profile
spring:
  profiles: docker

  ## MariaDB
  datasource:
    url: jdbc:mysql://mariadb:3306/sme
    username: dev
    password: devpass

  ## MongoDB
  data:
    mongodb:
      uri: mongodb://dev:devpass@mongodb

## Logging settings
logging.file: /app/log/sme-mts.log