resourcePackages:
- com.sme.mts.endpoint
prettyPrint: true
cacheTTL: 0
openAPI:
  info:
    title: 'SME-MTS(Money Transfer Service)'
    description: 'Find out more at [SME-MTS](https://github.com/hxh-robb/SME-MoneyTransferService/blob/sme/README.md)'
    version: '0.0.0(Demo)'
    contact:
      name: 'Robb'
      email: 'robb@smeinternet.com'
    license:
      name: MIT
      url: http://opensource.org/licenses/MIT
  tags:
    - name: '用户申请充值'
      description: '[接口调用流程](https://github.com/hxh-robb/SME-MoneyTransferService/blob/sme_1st_phase/docs/sme-mts-sdd.md#demo客户自主转账充值平台银行账号收款)'
    - name: '用户申请提款'
      description: '[接口调用流程](https://github.com/hxh-robb/SME-MoneyTransferService/blob/sme_1st_phase/docs/sme-mts-sdd.md#demo客户申请提款转账至客户银行账号)'
    - name: '资金账号'
      description: '资金账号CRUD接口'
    - name: '转账任务'
      description: '转账任务CRUD接口'
    - name: '元数据'
      description: '元数据CRUD接口'
  servers:
    - url: '/api'
      description: 'Newest version API'
    - url: '/api/v0'
      description: 'Demo API'