-- MySQL Script generated by MySQL Workbench
-- Fri 22 Dec 2017 11:41:47 AM PHT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ft
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `metadata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metadata` (
  `id` VARCHAR(64) NOT NULL COMMENT 'UUID',
  `ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  `de` TINYINT NOT NULL DEFAULT 0 COMMENT 'deleted flag',
  `name` VARCHAR(64) NOT NULL COMMENT 'metadata name',
  `catalog` VARCHAR(32) NOT NULL DEFAULT 'Undefined' COMMENT 'metadata catalog',
  `description` VARCHAR(256) NULL DEFAULT NULL COMMENT 'metadata description',
  `value` VARCHAR(32) NOT NULL COMMENT 'metadata value',
  `fields` BLOB NULL DEFAULT NULL COMMENT 'metadata dynamic fields',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'fund transfer service - metadata';

-- -----------------------------------------------------
-- Table `fund_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fund_account` (
  `id` VARCHAR(64) NOT NULL COMMENT 'UUID',
  `ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  `de` TINYINT NOT NULL DEFAULT 0 COMMENT 'deleted flag',
  `name` VARCHAR(64) NOT NULL COMMENT 'fund account name',
  `type` VARCHAR(32) NOT NULL COMMENT 'fund account type(FK, metadata.value)',
  `icon` VARCHAR(1024) NULL DEFAULT NULL COMMENT 'fund account icon image url',
  `fields` BLOB NULL DEFAULT NULL COMMENT 'fund account dynamic fields',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'fund transfer service - finance intermediary account';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
