-- MySQL Script generated by MySQL Workbench
-- Mon 15 Jan 2018 11:26:23 AM PHT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ft
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `fund_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fund_account` (
  `id` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL COMMENT 'UUID',
  `ct` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'creation time',
  `ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  `de` TINYINT(4) NOT NULL DEFAULT '0' COMMENT 'deleted flag',
  `name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL COMMENT 'fund account name',
  `type` VARCHAR(32) CHARACTER SET 'utf8' NOT NULL COMMENT 'fund account type(FK, metadata.value)',
  `icon` VARCHAR(1024) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT 'fund account icon image url',
  `fields` BLOB NULL DEFAULT NULL COMMENT 'fund account dynamic fields',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'fund transfer service - finance intermediary account';


-- -----------------------------------------------------
-- Table `metadata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metadata` (
  `id` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL COMMENT 'UUID',
  `ct` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'creation time',
  `ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  `de` TINYINT(4) NOT NULL DEFAULT '0' COMMENT 'deleted flag',
  `name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL COMMENT 'metadata name',
  `catalog` VARCHAR(32) CHARACTER SET 'utf8' NOT NULL DEFAULT 'UNDEFINED' COMMENT 'metadata catalog',
  `description` VARCHAR(256) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT 'metadata description',
  `value` VARCHAR(32) CHARACTER SET 'utf8' NOT NULL COMMENT 'metadata value',
  `fields` BLOB NULL DEFAULT NULL COMMENT 'metadata dynamic fields',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'fund transfer service - metadata';


-- -----------------------------------------------------
-- Table `transfer_task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transfer_task` (
  `id` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL COMMENT 'UUID',
  `ct` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'creation time',
  `ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  `de` TINYINT(4) NOT NULL DEFAULT '0' COMMENT 'deleted flag',
  `type` TINYINT(4) NOT NULL DEFAULT 0 COMMENT 'Transfer type: 0 for deposit; 1 for withdrawal;',
  `beneficiary` VARCHAR(64) NOT NULL COMMENT 'Beneficiary(player user id):\nIf it\'s a deposit task(cash in), then the benefit is credit adding;\nIf it\'s a withdrawal task(cash out), then the benefit is money transfer;',
  `platform` VARCHAR(64) NOT NULL COMMENT 'Source platform, which platform does this task belong to',
  `amount` DOUBLE NOT NULL COMMENT 'Fund amount, unit : CNY Yuan',
  `status` TINYINT(4) NOT NULL COMMENT 'Task status: 0 for success; 1 for pending;',
  `ref` VARCHAR(64) NOT NULL COMMENT 'Reference flag:\nBank deposit - the postscript;\nIntermediary deposit - order id;',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'fund transfer service - money transfer task';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
