spring:
  datasource:
    name: ft
    schema: classpath:database/schema.sql
    initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ft
    username: robb
    password: robbpass
    hikari:
      idle-timeout: 10000

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis-mappers/*.xml

#mongodb:
#  #address: "10.63.57.26:27017"
#  address: "127.0.0.1:27017"
#  username: "todo"
#  password: "todo"

logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}][%p][%c][%t]%m%n"
    #file: "[%d{yyyy-MM-dd HH:mm:ss}][%p][%c][%t]%m%n"
