spring:
#  main:
#    web-environment: false
#    banner-mode: false
  datasource:
    name: ft
    schema: classpath:database/schema.sql
    initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ft
    username: robb
    password: robbpass
    hikari:
      idle-timeout: 10000
  thymeleaf:
    cache: true
    check-template: true
    check-template-lockation: true
    content-type: text/html
    enabled: false
    encoding: UTF-8
    mode: HTML
    templateResolverOrder: 0

jsch:
  addr: 10.63.57.26
  port: 22
  user: robb
  password: robbpass

motan:
  zookeeper: 10.63.57.34:2181

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis-mappers/*.xml

#mongodb:
#  #address: "10.63.57.26:27017"
#  address: "127.0.0.1:27017"
#  username: "todo"
#  password: "todo"

logging:
  level:
    MetadataMapper: INFO
    FundAccountMapper: INFO
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}][%p][%c][%t]%m%n"
#    file: "[%d{yyyy-MM-dd HH:mm:ss}][%p][%c][%t]%m%n"
