## local environment settings
spring:
#  main:
#    web-environment: false
#    banner-mode: false
  datasource:
    name: ft
    schema: classpath:database/schema.sql
    initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ft
    username: robb
    password: robbpass
    hikari:
      idle-timeout: 10000
  thymeleaf:
    cache: true
    check-template: true
    check-template-lockation: true
    content-type: text/html
    enabled: false
    encoding: UTF-8
    mode: HTML
    templateResolverOrder: 0
  profiles:
    active: local

docs-dir:
  raw: /home/shared-files/raw/
  base: /home/shared-files/resources/
  urlBase: http://127.0.0.1:8888/resources/

sftp:
  host: 127.0.0.1
  port: 22
  username: shared-files
  password: shared-files-pass
  connectTimeout: 10000
  pool:
    maxTotal: 10
    maxIdle: 1
    maxWaitMillis: 10000

motan:
  zookeeper: 10.63.57.26:2181

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis-mappers/*.xml

#mongodb:
#  #address: "10.63.57.26:27017"
#  address: "127.0.0.1:27017"
#  username: "todo"
#  password: "todo"

logging:
  level:
    MetadataMapper: INFO
    FundAccountMapper: INFO
    serviceStatsLog: OFF # disable motan logger which is super annoying
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}][%p][%c][%t]%m%n"
#    file: "[%d{yyyy-MM-dd HH:mm:ss}][%p][%c][%t]%m%n"

---

## unit test environment settings
spring:
  profiles: unit-test
  datasource: # need to install MariaDB in local environment first
    schema: classpath:database/drop.sql, classpath:database/schema.sql
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ft_unit_test
    username: robb
    password: robbpass

---

## development environment settings
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://10.63.51.105:3306/pubplat_deposit
    username: bidev_deposit
    password: BIDEV_DEPOSIT

motan:
  zookeeper: 10.63.51.114:2181

---

## For test & production environment settings, please see /etc/outwit-ft-core/application.yml