spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/yourDbName
        username: root
        password: root
        driver-class-name: org.mariadb.jdbc.Driver

mongodb:
  #address: "10.63.57.26:27017"
  address: "127.0.0.1:27017"
  username: "todo"
  password: "todo"

logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}][%p][%c][%t]%m%n"
    #file: "[%d{yyyy-MM-dd HH:mm:ss}][%p][%c][%t]%m%n"
